travels = ['nannning','guilin','sanya','beihai','qinzhou']
print(f"Here is the original list: {travels}")
print(f"Here is the sorted list:{sorted(travels)}")
print(f"Here is the original list: {travels}")
print(f"Here is the sorted list:{sorted(travels,reverse=True)}")
print(f"Here is the original list: {travels}")
travels.reverse()
print(travels)
travels.reverse()
print(travels)
travels.sort()
print(travels)
travels.sort(reverse=True)
print(travels)